# wrangler.toml
name = "wheres-waldo"
compatibility_date = "2025-08-26"
main = "./src/api/index.jsx"
compatibility_flags = [ "nodejs_compat" ]

[[ d1_databases ]]
binding = "DB"
database_name = "wheres-waldo"
database_id = "34e4b893-7aaf-4c4d-80bd-f5b2b9f83b90"
migrations_dir = "drizzle"

[assets]
not_found_handling = "single-page-application"